# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afiliadoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_afil_win(object):
    def setupUi(self, afil_win):
        afil_win.setObjectName("afil_win")
        afil_win.resize(800, 600)
        afil_win.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(afil_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 111))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 81, 181);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.push_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.push_guardar.setGeometry(QtCore.QRect(550, 420, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_guardar.setFont(font)
        self.push_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_guardar.setStyleSheet("\n"
"color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_guardar.setObjectName("push_guardar")
        self.push_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.push_regresar.setGeometry(QtCore.QRect(30, 40, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_regresar.setFont(font)
        self.push_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_regresar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_regresar.setObjectName("push_regresar")
        self.line_ide = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ide.setGeometry(QtCore.QRect(30, 190, 151, 20))
        self.line_ide.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_ide.setMaxLength(12)
        self.line_ide.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_ide.setObjectName("line_ide")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 151, 16))
        self.label_2.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nombre.setGeometry(QtCore.QRect(220, 190, 151, 20))
        self.line_nombre.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_nombre.setMaxLength(22)
        self.line_nombre.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_nombre.setObjectName("line_nombre")
        self.line_apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.line_apellido.setGeometry(QtCore.QRect(410, 190, 151, 20))
        self.line_apellido.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_apellido.setMaxLength(22)
        self.line_apellido.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_apellido.setObjectName("line_apellido")
        self.line_direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.line_direccion.setGeometry(QtCore.QRect(600, 190, 151, 20))
        self.line_direccion.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_direccion.setMaxLength(22)
        self.line_direccion.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_direccion.setObjectName("line_direccion")
        self.line_correo = QtWidgets.QLineEdit(self.centralwidget)
        self.line_correo.setGeometry(QtCore.QRect(30, 270, 151, 20))
        self.line_correo.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_correo.setMaxLength(40)
        self.line_correo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_correo.setObjectName("line_correo")
        self.line_telefono = QtWidgets.QLineEdit(self.centralwidget)
        self.line_telefono.setGeometry(QtCore.QRect(220, 270, 151, 20))
        self.line_telefono.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_telefono.setMaxLength(22)
        self.line_telefono.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_telefono.setObjectName("line_telefono")
        self.line_ciudad = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ciudad.setGeometry(QtCore.QRect(410, 270, 151, 20))
        self.line_ciudad.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_ciudad.setMaxLength(30)
        self.line_ciudad.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_ciudad.setObjectName("line_ciudad")
        self.line_show_date = QtWidgets.QLineEdit(self.centralwidget)
        self.line_show_date.setGeometry(QtCore.QRect(600, 270, 151, 20))
        self.line_show_date.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_show_date.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_show_date.setReadOnly(True)
        self.line_show_date.setObjectName("line_show_date")
        self.calendar_nacimiento = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar_nacimiento.setGeometry(QtCore.QRect(90, 340, 312, 183))
        self.calendar_nacimiento.setStyleSheet("color: rgb(0, 0, 0);")
        self.calendar_nacimiento.setObjectName("calendar_nacimiento")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(550, 340, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("color: rgb(116, 116, 116);\n"
"border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 170, 151, 16))
        self.label_3.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 170, 151, 16))
        self.label_4.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 170, 151, 16))
        self.label_5.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 151, 16))
        self.label_6.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 250, 151, 16))
        self.label_7.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(600, 250, 151, 16))
        self.label_8.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 250, 151, 16))
        self.label_9.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_ide = QtWidgets.QLabel(self.centralwidget)
        self.label_ide.setGeometry(QtCore.QRect(30, 210, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_ide.setFont(font)
        self.label_ide.setStyleSheet("color: rgb(233, 30, 99);")
        self.label_ide.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ide.setObjectName("label_ide")
        self.label_correo = QtWidgets.QLabel(self.centralwidget)
        self.label_correo.setGeometry(QtCore.QRect(30, 290, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_correo.setFont(font)
        self.label_correo.setStyleSheet("color: rgb(233, 30, 99);")
        self.label_correo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_correo.setObjectName("label_correo")
        self.label_telefono = QtWidgets.QLabel(self.centralwidget)
        self.label_telefono.setGeometry(QtCore.QRect(220, 290, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_telefono.setFont(font)
        self.label_telefono.setStyleSheet("color: rgb(233, 30, 99);")
        self.label_telefono.setAlignment(QtCore.Qt.AlignCenter)
        self.label_telefono.setObjectName("label_telefono")
        self.check_desafiliado = QtWidgets.QCheckBox(self.centralwidget)
        self.check_desafiliado.setGeometry(QtCore.QRect(610, 340, 81, 31))
        self.check_desafiliado.setStyleSheet("color: rgb(116, 116, 116);\n"
"border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.check_desafiliado.setObjectName("check_desafiliado")
        afil_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(afil_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        afil_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(afil_win)
        self.statusbar.setObjectName("statusbar")
        afil_win.setStatusBar(self.statusbar)

        self.retranslateUi(afil_win)
        QtCore.QMetaObject.connectSlotsByName(afil_win)

    def retranslateUi(self, afil_win):
        _translate = QtCore.QCoreApplication.translate
        afil_win.setWindowTitle(_translate("afil_win", "Ingreso Afiliados"))
        self.label.setText(_translate("afil_win", "INGRESAR AFILIADO"))
        self.push_guardar.setText(_translate("afil_win", "Guardar"))
        self.push_regresar.setText(_translate("afil_win", "Regresar"))
        self.label_2.setText(_translate("afil_win", "Numero de identificación"))
        self.checkBox.setText(_translate("afil_win", "Vacunado"))
        self.label_3.setText(_translate("afil_win", "Nombre"))
        self.label_4.setText(_translate("afil_win", "Apellido"))
        self.label_5.setText(_translate("afil_win", "Dirección"))
        self.label_6.setText(_translate("afil_win", "Correo"))
        self.label_7.setText(_translate("afil_win", "Telefono"))
        self.label_8.setText(_translate("afil_win", "Fecha de Nacimiento"))
        self.label_9.setText(_translate("afil_win", "Ciudad de Residencia"))
        self.label_ide.setText(_translate("afil_win", "Menos de 6 Digitos"))
        self.label_correo.setText(_translate("afil_win", "Debe tener un @ y un ."))
        self.label_telefono.setText(_translate("afil_win", "Menos de 6 Digitos"))
        self.check_desafiliado.setText(_translate("afil_win", "Desafiliado"))
