# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afiliadoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_afil_win(object):
    def setupUi(self, afil_win):
        afil_win.setObjectName("afil_win")
        afil_win.resize(790, 491)
        afil_win.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(afil_win)
        self.centralwidget.setObjectName("centralwidget")
        self.line_ide = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ide.setGeometry(QtCore.QRect(10, 110, 181, 41))
        self.line_ide.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_ide.setMaxLength(10)
        self.line_ide.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_ide.setObjectName("line_ide")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 181, 16))
        self.label.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.push_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.push_guardar.setGeometry(QtCore.QRect(560, 340, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_guardar.setFont(font)
        self.push_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_guardar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_guardar.setObjectName("push_guardar")
        self.push_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.push_regresar.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_regresar.setFont(font)
        self.push_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_regresar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_regresar.setObjectName("push_regresar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 110, 181, 16))
        self.label_2.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nombre.setGeometry(QtCore.QRect(210, 120, 181, 31))
        self.line_nombre.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_nombre.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_nombre.setObjectName("line_nombre")
        self.line_apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.line_apellido.setGeometry(QtCore.QRect(404, 120, 181, 31))
        self.line_apellido.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_apellido.setText("")
        self.line_apellido.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_apellido.setObjectName("line_apellido")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 110, 171, 20))
        self.label_3.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.line_direccion.setGeometry(QtCore.QRect(600, 120, 181, 31))
        self.line_direccion.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_direccion.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_direccion.setObjectName("line_direccion")
        self.line_telefono = QtWidgets.QLineEdit(self.centralwidget)
        self.line_telefono.setGeometry(QtCore.QRect(204, 180, 181, 31))
        self.line_telefono.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_telefono.setText("")
        self.line_telefono.setMaxLength(10)
        self.line_telefono.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_telefono.setObjectName("line_telefono")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 110, 181, 20))
        self.label_4.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 170, 171, 16))
        self.label_5.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 181, 16))
        self.label_6.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.line_correo = QtWidgets.QLineEdit(self.centralwidget)
        self.line_correo.setGeometry(QtCore.QRect(10, 179, 181, 31))
        self.line_correo.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_correo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_correo.setObjectName("line_correo")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 170, 181, 16))
        self.label_7.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.line_ciudad = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ciudad.setGeometry(QtCore.QRect(400, 180, 181, 31))
        self.line_ciudad.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_ciudad.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_ciudad.setObjectName("line_ciudad")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(600, 170, 181, 20))
        self.label_8.setStyleSheet("\n"
"color: rgb(116, 116, 116);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(560, 250, 71, 31))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setStyleSheet("color: rgb(116, 116, 116);\n"
"border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.calendar_nacimiento = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar_nacimiento.setGeometry(QtCore.QRect(120, 230, 321, 211))
        self.calendar_nacimiento.setStyleSheet("color: rgb(0, 0, 0);")
        self.calendar_nacimiento.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendar_nacimiento.setGridVisible(True)
        self.calendar_nacimiento.setNavigationBarVisible(True)
        self.calendar_nacimiento.setDateEditEnabled(True)
        self.calendar_nacimiento.setObjectName("calendar_nacimiento")
        self.line_show_date = QtWidgets.QLineEdit(self.centralwidget)
        self.line_show_date.setGeometry(QtCore.QRect(600, 180, 181, 31))
        self.line_show_date.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_show_date.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_show_date.setReadOnly(True)
        self.line_show_date.setObjectName("line_show_date")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 791, 71))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 81, 181);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.line_show_date.raise_()
        self.line_correo.raise_()
        self.line_ciudad.raise_()
        self.line_nombre.raise_()
        self.line_ide.raise_()
        self.label.raise_()
        self.push_guardar.raise_()
        self.push_regresar.raise_()
        self.label_2.raise_()
        self.line_apellido.raise_()
        self.label_3.raise_()
        self.line_direccion.raise_()
        self.line_telefono.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.checkBox.raise_()
        self.calendar_nacimiento.raise_()
        afil_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(afil_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        afil_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(afil_win)
        self.statusbar.setObjectName("statusbar")
        afil_win.setStatusBar(self.statusbar)

        self.retranslateUi(afil_win)
        QtCore.QMetaObject.connectSlotsByName(afil_win)

    def retranslateUi(self, afil_win):
        _translate = QtCore.QCoreApplication.translate
        afil_win.setWindowTitle(_translate("afil_win", "Afiliados"))
        self.label.setText(_translate("afil_win", "Numero de identificacion"))
        self.push_guardar.setText(_translate("afil_win", "Guardar"))
        self.push_regresar.setText(_translate("afil_win", "Regresar"))
        self.label_2.setText(_translate("afil_win", "Nombre"))
        self.label_3.setText(_translate("afil_win", "Apellido"))
        self.label_4.setText(_translate("afil_win", "Direccion"))
        self.label_5.setText(_translate("afil_win", "Telefono"))
        self.label_6.setText(_translate("afil_win", "Correo"))
        self.label_7.setText(_translate("afil_win", "Ciudad de Residencia"))
        self.label_8.setText(_translate("afil_win", "Fecha de Nacimiento"))
        self.checkBox.setText(_translate("afil_win", "Vacunado"))
        self.label_10.setText(_translate("afil_win", "INGRESAR AFILIADO"))
