# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'citasUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_citas(object):
    def setupUi(self, citas):
        citas.setObjectName("citas")
        citas.resize(371, 582)
        citas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(citas)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 200, 312, 183))
        self.calendarWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setObjectName("calendarWidget")
        self.line_show_date = QtWidgets.QLineEdit(self.centralwidget)
        self.line_show_date.setGeometry(QtCore.QRect(110, 150, 151, 20))
        self.line_show_date.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.line_show_date.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line_show_date.setReadOnly(True)
        self.line_show_date.setObjectName("line_show_date")
        self.push_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.push_calcular.setGeometry(QtCore.QRect(150, 500, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_calcular.setFont(font)
        self.push_calcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_calcular.setStyleSheet("\n"
"color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_calcular.setObjectName("push_calcular")
        self.spin_hour = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_hour.setGeometry(QtCore.QRect(130, 440, 42, 21))
        self.spin_hour.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.spin_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_hour.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spin_hour.setMaximum(23)
        self.spin_hour.setObjectName("spin_hour")
        self.spin_minute = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_minute.setGeometry(QtCore.QRect(200, 440, 42, 22))
        self.spin_minute.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.spin_minute.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_minute.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spin_minute.setMaximum(30)
        self.spin_minute.setSingleStep(30)
        self.spin_minute.setObjectName("spin_minute")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 440, 16, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 371, 111))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 81, 181);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.push_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.push_regresar.setGeometry(QtCore.QRect(10, 40, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_regresar.setFont(font)
        self.push_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_regresar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_regresar.setObjectName("push_regresar")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(110, 170, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("color: rgb(233, 30, 99);")
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 410, 111, 20))
        self.label_3.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 130, 151, 16))
        self.label_4.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        citas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(citas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        citas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(citas)
        self.statusbar.setObjectName("statusbar")
        citas.setStatusBar(self.statusbar)

        self.retranslateUi(citas)
        QtCore.QMetaObject.connectSlotsByName(citas)

    def retranslateUi(self, citas):
        _translate = QtCore.QCoreApplication.translate
        citas.setWindowTitle(_translate("citas", "Citas"))
        self.push_calcular.setText(_translate("citas", "Calcular"))
        self.label.setText(_translate("citas", ":"))
        self.label_2.setText(_translate("citas", "CITAS"))
        self.push_regresar.setText(_translate("citas", "Regresar"))
        self.label_date.setText(_translate("citas", "La Hora y Fecha Deben Ser Futuras"))
        self.label_3.setText(_translate("citas", "Hora de Inicio"))
        self.label_4.setText(_translate("citas", "Fecha de Inicio"))
