# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CrearPlan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrearPlanWindow(object):
    def setupUi(self, CrearPlanWindow):
        CrearPlanWindow.setObjectName("CrearPlanWindow")
        CrearPlanWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        CrearPlanWindow.setFont(font)
        CrearPlanWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(CrearPlanWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(0, 0, 801, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("background-color: rgb(63, 81, 181);\n"
"color: rgb(255, 255, 255);")
        self.label_titulo.setObjectName("label_titulo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 140, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 230, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_FechaInicio = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FechaInicio.setGeometry(QtCore.QRect(90, 170, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lineEdit_FechaInicio.setFont(font)
        self.lineEdit_FechaInicio.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.lineEdit_FechaInicio.setReadOnly(True)
        self.lineEdit_FechaInicio.setObjectName("lineEdit_FechaInicio")
        self.pushButton_Guardar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Guardar.setGeometry(QtCore.QRect(490, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Guardar.setFont(font)
        self.pushButton_Guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Guardar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 15px;")
        self.pushButton_Guardar.setObjectName("pushButton_Guardar")
        self.pushButton_Regresar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Regresar.setGeometry(QtCore.QRect(10, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Regresar.setFont(font)
        self.pushButton_Regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Regresar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 15px;")
        self.pushButton_Regresar.setObjectName("pushButton_Regresar")
        self.calendar_fechaInicio = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar_fechaInicio.setGeometry(QtCore.QRect(50, 230, 312, 183))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.calendar_fechaInicio.setFont(font)
        self.calendar_fechaInicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendar_fechaInicio.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.calendar_fechaInicio.setObjectName("calendar_fechaInicio")
        self.spinBox_Min = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Min.setGeometry(QtCore.QRect(460, 170, 171, 22))
        self.spinBox_Min.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.spinBox_Min.setObjectName("spinBox_Min")
        self.spinBox_Max = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Max.setGeometry(QtCore.QRect(460, 260, 171, 22))
        self.spinBox_Max.setStyleSheet("border-width: 2px; \n"
"border-style: solid; \n"
"border-color: white white rgb(233, 30, 99) white;")
        self.spinBox_Max.setObjectName("spinBox_Max")
        CrearPlanWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CrearPlanWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        CrearPlanWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CrearPlanWindow)
        self.statusbar.setObjectName("statusbar")
        CrearPlanWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CrearPlanWindow)
        QtCore.QMetaObject.connectSlotsByName(CrearPlanWindow)

    def retranslateUi(self, CrearPlanWindow):
        _translate = QtCore.QCoreApplication.translate
        CrearPlanWindow.setWindowTitle(_translate("CrearPlanWindow", "Crear Plan"))
        self.label_titulo.setText(_translate("CrearPlanWindow", "<html><head/><body><p align=\"center\">CREAR PLAN DE VACUNACIÓN</p></body></html>"))
        self.label_3.setText(_translate("CrearPlanWindow", "Fecha de inicio"))
        self.label_4.setText(_translate("CrearPlanWindow", "Edad mínima para clasificar"))
        self.label_5.setText(_translate("CrearPlanWindow", "Edad máxima para clasificar"))
        self.pushButton_Guardar.setText(_translate("CrearPlanWindow", "Guardar"))
        self.pushButton_Regresar.setText(_translate("CrearPlanWindow", "Regresar"))
