# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_lote.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_edit(object):
    def setupUi(self, Dialog_edit):
        Dialog_edit.setObjectName("Dialog_edit")
        Dialog_edit.resize(372, 155)
        Dialog_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.combo_carga = QtWidgets.QComboBox(Dialog_edit)
        self.combo_carga.setGeometry(QtCore.QRect(80, 60, 231, 22))
        self.combo_carga.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.combo_carga.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-bottom-color:  rgb(233, 30, 99) ;")
        self.combo_carga.setObjectName("combo_carga")
        self.push_aceptar = QtWidgets.QPushButton(Dialog_edit)
        self.push_aceptar.setGeometry(QtCore.QRect(100, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_aceptar.setFont(font)
        self.push_aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_aceptar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_aceptar.setObjectName("push_aceptar")
        self.push_cancelar = QtWidgets.QPushButton(Dialog_edit)
        self.push_cancelar.setGeometry(QtCore.QRect(210, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.push_cancelar.setFont(font)
        self.push_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_cancelar.setStyleSheet("color: rgb(63, 81, 181);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(63, 81, 181);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_cancelar.setObjectName("push_cancelar")
        self.label = QtWidgets.QLabel(Dialog_edit)
        self.label.setGeometry(QtCore.QRect(80, 30, 231, 20))
        self.label.setStyleSheet("color:rgb(116, 116, 116);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_edit)
        QtCore.QMetaObject.connectSlotsByName(Dialog_edit)

    def retranslateUi(self, Dialog_edit):
        _translate = QtCore.QCoreApplication.translate
        Dialog_edit.setWindowTitle(_translate("Dialog_edit", "Editar Lote"))
        self.push_aceptar.setText(_translate("Dialog_edit", "Editar"))
        self.push_cancelar.setText(_translate("Dialog_edit", "Cancelar"))
        self.label.setText(_translate("Dialog_edit", "Seleccione el Lote a Editar"))
