# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_citas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_citas(object):
    def setupUi(self, menu_citas):
        menu_citas.setObjectName("menu_citas")
        menu_citas.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(menu_citas)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 81))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(63, 81, 181);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.push_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.push_calcular.setGeometry(QtCore.QRect(280, 160, 241, 31))
        self.push_calcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_calcular.setStyleSheet("color:rgb(46, 26, 162) ;\n"
"border-style: outset;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(46, 26, 162);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_calcular.setObjectName("push_calcular")
        self.push_ver = QtWidgets.QPushButton(self.centralwidget)
        self.push_ver.setGeometry(QtCore.QRect(280, 300, 241, 31))
        self.push_ver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_ver.setStyleSheet("color:rgb(46, 26, 162) ;\n"
"border-style: outset;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(46, 26, 162);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_ver.setObjectName("push_ver")
        self.push_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.push_regresar.setGeometry(QtCore.QRect(280, 370, 241, 31))
        self.push_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_regresar.setStyleSheet("color:rgb(46, 26, 162) ;\n"
"border-style: outset;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(46, 26, 162);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_regresar.setObjectName("push_regresar")
        self.push_consultar = QtWidgets.QPushButton(self.centralwidget)
        self.push_consultar.setGeometry(QtCore.QRect(280, 230, 241, 31))
        self.push_consultar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_consultar.setStyleSheet("color:rgb(46, 26, 162) ;\n"
"border-style: outset;\n"
"background-color:rgb(255, 255, 255) ;\n"
"border-color:rgb(46, 26, 162);\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.push_consultar.setObjectName("push_consultar")
        menu_citas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menu_citas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        menu_citas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menu_citas)
        self.statusbar.setObjectName("statusbar")
        menu_citas.setStatusBar(self.statusbar)

        self.retranslateUi(menu_citas)
        QtCore.QMetaObject.connectSlotsByName(menu_citas)

    def retranslateUi(self, menu_citas):
        _translate = QtCore.QCoreApplication.translate
        menu_citas.setWindowTitle(_translate("menu_citas", "Menu Afiliados"))
        self.label.setText(_translate("menu_citas", "CITAS"))
        self.push_calcular.setText(_translate("menu_citas", "CALCULAR"))
        self.push_ver.setText(_translate("menu_citas", "VER TODO"))
        self.push_regresar.setText(_translate("menu_citas", "REGRESAR"))
        self.push_consultar.setText(_translate("menu_citas", "CONSULTAR"))
